include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: 
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    use_function_type_syntax_for_parameters: false