name: instagram_clone
description: A new Flutter project.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^0.1.0
  get_it: ^3.1.0
  built_value: ^7.0.8
  built_collection: ^4.3.2
  super_enum: ^0.4.0
  flutter_bloc: ^3.2.0
  equatable: ^1.0.3
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  timeago: ^2.0.22
  chopper: ^3.0.1+1
  flutter_stetho: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8
  super_enum_generator: ^0.4.0
  chopper_generator: ^3.0.0
  injectable_generator: ^0.1.0
  mockito: ^4.1.0

flutter:
  uses-material-design: true