name: instagram_clone
description: A new Flutter project.

version: 1.0.4+5

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+2
  flutter_native_image: ^0.0.5+2
  image_crop: ^0.3.2
  image_picker: ^0.6.7+4
  path_provider: ^1.6.0
  path: ^1.6.4
  injectable: ^1.0.2
  get_it: ^4.0.4
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  http: ^0.12.2
  shared_preferences: ^0.5.8
  timeago: ^2.0.22
  chopper: ^3.0.3
  flutter_stetho: ^0.5.2
  rxdart: ^0.24.1
  flutter_dotenv: ^2.1.0
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.2
  bloc_test: ^7.0.2
  build_runner: ^1.7.3
  chopper_generator: ^3.0.5
  injectable_generator: ^1.0.2
  mockito: ^4.1.0
  freezed: ^0.12.1
  pedantic: ^1.9.0

dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true
  assets:
    - .env/
    - assets/
    