name: instagram_clone
description: A new Flutter project.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^0.1.0
  built_value: ^6.3.0
  built_collection: ^4.1.0
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  http: ^0.12.0+2
  flutter_stetho: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.3.0
  mockito: ^4.1.0

flutter:
  uses-material-design: true