name: instagram_clone
description: A new Flutter project.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.7+3
  flutter_native_image: ^0.0.5
  image_crop: ^0.3.2
  image_picker: ^0.6.3+4
  path_provider: ^1.6.0
  path: ^1.6.4
  injectable: ^0.3.0
  get_it: ^4.0.0
  built_value: ^7.0.9
  built_collection: ^4.3.2
  super_enum: ^0.4.2
  flutter_bloc: ^3.2.0
  equatable: ^1.0.3
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  timeago: ^2.0.22
  chopper: ^3.0.2
  flutter_stetho: ^0.5.2
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  built_value_generator: ^7.0.9
  super_enum_generator: ^0.5.0
  chopper_generator: ^3.0.4
  injectable_generator: ^0.3.1
  mockito: ^4.1.0

flutter:
  uses-material-design: true